CREATE TABLE Majors
(
MajorID INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(50) NOT NULL
)

CREATE TABLE UniversityStudents
(
StudentID INT PRIMARY KEY IDENTITY,
StudentNumber VARCHAR(10) NOT NULL,
StudentName VARCHAR(50) NOT NULL,
MajorID INT FOREIGN KEY REFERENCES Majors(MajorID)
)

CREATE TABLE Subjects
(
SubjectID INT PRIMARY KEY IDENTITY,
[SubjectName] VARCHAR(50) NOT NULL
)

CREATE TABLE Agenda
(
SubjectID INT FOREIGN KEY REFERENCES Subjects(SubjectID),
StudentID INT FOREIGN KEY REFERENCES UniversityStudents(StudentID),
PRIMARY KEY(SubjectID, StudentID)
)

CREATE TABLE Payments
(
PaymentID INT PRIMARY KEY IDENTITY,
PaymentDate DATE NOT NULL,
PaymentAmount DECIMAL(10,2) NOT NULL,
StudentID INT FOREIGN KEY REFERENCES UniversityStudents(StudentID)
)